# Generated by Django 3.1 on 2021-12-03 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artike',
            new_name='Artikel',
        ),
    ]
